### ISSUE TITLE
Set up ElasticSearch and Kibana

### ISSUE THREAD

**Issue by priya299** [priya299/outreachy-project#1]
To create a working deployment of ElasticSearch and Kibana.

**Comment by priya299** [comment]
I have created a demo dashboard in Kibana following the [tutorial](https://www.elastic.co/guide/en/kibana/current/getting-started.html) 
Firstly, I downloaded elasticsearch zip file from [Elasticsearch page](https://www.elastic.co/products/elasticsearch). Then I extracted it and ran 'bin/elasticsearch' command after entering that particular directory. After that I used  'curl -X GET http://localhost:9200/' in terminal to connect to localhost. Now elasticsearch is set up.

This is how it looks like when elasticsearch is running.
![elasticsearch](https://cloud.githubusercontent.com/assets/17764649/15925128/93594fbe-2e53-11e6-81a5-a7bd3b1fa1bd.png)

Next I set up Kibana. It is also done in similar way. Only thing is that you need to install elasticsearch  before kibana. From the link for [kibana ](https://www.elastic.co/downloads/kibana) I downloaded kibana zip file. Then I extracted it. In the kibana file, I set the elasticsearch.url to point at my elasticsearch instance, in config/kibana.yml file. (set it to point at http://yourhost.com:5601) then I got the kibana working when I ran ./bin/kibana command. 

Running Kibana,
![kibana1](https://cloud.githubusercontent.com/assets/17764649/15925166/b591e94c-2e53-11e6-9aaf-0c8cdf3d13f3.png)

Now when I browsed the link shown in the terminal, Kibana gets started.
![kibana2](https://cloud.githubusercontent.com/assets/17764649/15925283/21dd3db8-2e54-11e6-843a-a4eb7db6b410.png)

After setting up Kibana and Elasticsearch, the next step was to add data to Elasticsearch so as to visualize it in Kibana later.

For this, I downloaded three sample json files and added them to elasticsearch by the following steps:
1.  Create an index for the three json files using curl.  Follow this [link.](https://www.elastic.co/guide/en/kibana/current/getting-started.html)
2.  Run 'curl -XPOST 'yourhost:9200/jsonfilename/_bulk?pretty' --data-binary @jsonfilename.json
   Now elasticsearch will have 3 indexes corresponding to each of the json files.

Next, for visualizing these different files in different manners, like, using pie-charts, bar-graphs etc, we just need to add these indexes to kibana by browsing them from our local directory. This link will help with [visualizations in Kibana.](https://www.elastic.co/guide/en/kibana/current/tutorial-visualizing.html) 

Following the tutorial I have created the following Dashboard. We can easily save many visualizations and Dashboards created in Kibana.
![kibana3](https://cloud.githubusercontent.com/assets/17764649/15926487/f1a73efe-2e59-11e6-88e7-e76105f73294.png)

**Comment by jgbarah** [comment]
Good! When I have permissions, I close this ticket.

**Comment by priya299** [comment]
Thank you.
Sorry, I forgot about that. I have given the permission.
