### ISSUE TITLE
Tests for threading code

### ISSUE THREAD

**Issue by priya299** [priya299/outreachy-project#2]
Implementing tests for mbox mails.

**Comment by priya299** [comment]
I have implemented the test-case for the threading code. The code can be seen [here](https://github.com/priya299/Dashboard/blob/master/tests/test.py). 
Here it checks whether the count of Message IDs in [jwzthreading_r.py](https://github.com/priya299/Dashboard/blob/master/jwzthreading_r.py) is one greater than the count of property_id in testoutput.json file created using [testing code](https://github.com/priya299/Dashboard/blob/master/tests/test.py). 
Test commit can be seen [here](https://github.com/priya299/Dashboard/commit/2b09bf24bbd8db633af809780f47836c012b0c16).

**Comment by jgbarah** [comment]
Thanks. We will probably come back to this later, to have more comprehensive tests. But for now, I'm closing this (well, I would if you give permission to me ;-) ).
